// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzgKSpRVi0FXaZ84fOPezWj-vSIGgWlr4',
    appId: '1:678672499778:web:639371c0b6856dfd8859db',
    messagingSenderId: '678672499778',
    projectId: 'skill-todo-fb',
    authDomain: 'skill-todo-fb.firebaseapp.com',
    storageBucket: 'skill-todo-fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF-rpcZe_fTJUl1j28UAHiaRPjQ-ZYUPQ',
    appId: '1:678672499778:android:e539236be8709fd88859db',
    messagingSenderId: '678672499778',
    projectId: 'skill-todo-fb',
    storageBucket: 'skill-todo-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtv0uAEoODcEA1Cz2eeOnMbWCFIleujZ8',
    appId: '1:678672499778:ios:620cab4ca2c797398859db',
    messagingSenderId: '678672499778',
    projectId: 'skill-todo-fb',
    storageBucket: 'skill-todo-fb.appspot.com',
    iosClientId: '678672499778-65ldv7hn1ft6uiqfs3cknd0fn7m9n4nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtv0uAEoODcEA1Cz2eeOnMbWCFIleujZ8',
    appId: '1:678672499778:ios:620cab4ca2c797398859db',
    messagingSenderId: '678672499778',
    projectId: 'skill-todo-fb',
    storageBucket: 'skill-todo-fb.appspot.com',
    iosClientId: '678672499778-65ldv7hn1ft6uiqfs3cknd0fn7m9n4nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebase',
  );
}
